### ISSUE TITLE
Passwords with spaces do not work

### ISSUE THREAD

**Issue by liadavies** [jflm/sspm#1]
When I use a password with a space in it, only the characters before the space are copied to the clipboard. 

For example:

If my password was _A password_, only the A would be copied to the clipboard.

**Comment by jflm** [comment]
Hi @liadavies thanks so much for getting in touch!

Unfortunately spaces in passwords is a premium feature and you would need to upgrade to SSPM Premium in order to access 'space functionality'.

For just $14.99 a month you can get **_unlimited_** spaces in passwords, it's really worth it!

Thanks again for being a SSPM user!

**Comment by jflm** [comment]
I am obviously 100% joking. Thanks for highlighting, I will take a look. My guess is it's something to do with a n00b variable interpolation mistake.
